version: '2'
services:
    app1-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/app1/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=app1
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
